services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
        POSTGRES_USER: pharmaFind
        POSTGRES_PASSWORD: secret
        POSTGRES_DB: pharmaFind
        PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/data/postgres
    ports:
        - 5432:5432
    networks:
        - pharmaFind
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev
    image: maildev/maildev
    ports:
        - 1080:1080
        - 1025:1025
    networks:
        - pharmaFind
    restart: unless-stopped
    
  minio:
    container_name: minio
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    networks:
      - pharmaFind
    volumes:
      - minio:/minio/data
    restart: unless-stopped

networks:
    pharmaFind:
        driver: bridge

volumes:
    postgres:
      driver: local
    minio:
      driver: local
