spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pharmaFind
    username: pharmaFind
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: admin
    password: admin
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
  docker:
    compose:
      lifecycle-management: start_and_stop
      stop:
        command: down

application:
  security:
    jwt:
      secret-key: l4XHRo3eMZoNADQJFK5fG6sCuJSRAFnQ
      expiration: 86400000
  mailing:
    frontend:
      activation-url: http://localhost:5173/activate-account
  storage:
    minio:
      url: http://localhost:9000
      accessKey: minioadmin
      secretKey: minioadmin
      bucket-name: pharmafind-bucket
      secure: false